### ISSUE TITLE
Run all migrations in the same transaction

### ISSUE THREAD

**Issue by porsager** [porsager/pg-shift#1]
I'm thinking it might be good if all pending migrations are run inside the same transaction.

Currently if more than one migration is pending they will run in separate transactions allowing for any to finish even though a later one fails. 

This might not be expected if doing a deploy where the system is expecting migrations to be up to date when running subsequent services. In that case it would probably be better with a rollback, and then user land can decide if that's handled by chceking out the previous commit or handle the error manually.

What do you think @JAForbes ?

**Comment by JAForbes** [comment]
I think by default it should be one transaction.  👍
